services:
  frontend:
    image: node:18
    container_name: frontend
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
    ports:
      - "3000:3000"
    # command: sh -c "npm install && npm run build && npm start"
    command: sh -c "npm run dev"

  backend:
    image: node:18
    container_name: backend
    working_dir: /backend
    volumes:
      - ./backend/:/backend
      # - /backend/node_modules
    ports:
      - "4000:4000"
    command: sh -c "npm run docker"
    depends_on:
      mysql:
        condition: service_healthy
      
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - frontend

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neuman@123
      MYSQL_DATABASE: neuman
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mysql_data: